spring.application.name=EmployeeManagementSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=postgres
spring.datasource.password=@Abhi_1606
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SERVER PORT
server.port=8080

# =========================
# MAIL CONFIGURATION
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=abhidhage987@gmail.com
spring.mail.password=isjz ippx tsdk hdwt

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SSL/TLS FIX
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2